### PR TITLE
README: Add Node.js 6 to supported versions.

### PR DESCRIPTION
**Pull request by coderbyheart**
The support was added in sass/node-sass#1499

### CODE REVIEW

**Comment by xzyfer** [comment]
Thank you. I'm putting this off until we ship 3.7.0

**Comment by coderbyheart** [comment]
Of course, just wanted to make sure that the README is accurate.

**Comment by Zorgatone** [comment]
Is Node 6 supported??

I still get the `Error: Node Sass does not yet support your current environment: Windows 64-bit with false` error

**Comment by xzyfer** [comment]
It's not, which is why this hasn't been merged.

**Comment by Zorgatone** [comment]
Oh, ok. :+1:

**Pull request merged**
