### PR TITLE
Repo: Adds .gitattributes

### PR DESCRIPTION
**Pull request by am11**
Issue URL: #758.

//cc @mgreter

### CODE REVIEW

**Comment by kevva** [comment]
This feels like something that should be set on the user level imo.

**Comment by am11** [comment]
@kevva, it shouldn't be part of repo?

**Comment by kevva** [comment]
Well, ideally, contributors would have this setup in their editors, but I guess that's not always the case.

**Comment by xzyfer** [comment]
http://editorconfig.org/ might also be worth a look

**Comment by xzyfer** [comment]
:+1:

**Comment by mgreter** [comment]
@kevva IMO it's a must to have a `.gitattributes` file for projects that are intended to work across multiple architectures. The file @am11 used as the base here has been in use by me since a few years, and I didn't just add it for the "fun" of adding it! The libsass team faces the same issue with the spec tests, since they currently are checked out either with `\r\n` or `\n`, according to the running OS. The spec-runner currently needs to normalize these linefeeds before comparing the results. In case of libsass this is actually desired, since we should use `\r\n` as the default linefeed when running on windows!

**Comment by am11** [comment]
@mgreter, forgot to add `node-sass` (the main node entry-point for CLI) itself. :)

@xzyfer, the `.editorconfig` is already setup for this repo. In VS, it even gives me intellisense in .editorconfig file due to this https://github.com/editorconfig/editorconfig-visualstudio/pull/12! It seems like git was normalising all files because lack of `.gitattributes`. I think npm can also use something like `.npmattributes` to address https://github.com/npm/npm/issues/2097.

**Pull request merged**
