### PR TITLE
Support for aarch64 

### PR DESCRIPTION
**Pull request by ossdev07**
Hi, 

I have provided drone.yml file 97d1c75 so that it could be tested on the aarch64 platform as per the aarch64 related changes provided in the 2651e9f.

Please consider the PR for the merge, do let me know if anything else is required from my end.

### CODE REVIEW

**Comment by xzyfer** [comment]
Thanks! I've enabled drone.io on this repo. We'll play around with it.

**Comment by xzyfer** [comment]
I'm going to close this PR and open a branch on this repo we can experiment with.

**Comment by ossdev07** [comment]
Thanks for the reply @xzyfer 

Do you want any other changes in the drone.yml file, please let me know.

It will be a delight to see the release of binary for the aarch64 platform.

**Comment by xzyfer** [comment]
@ossdev07 I've opened #2647 to keep poking around. It probably be a while before we're able to do a release with arm.

**Pull request closed without merging**
