### PR TITLE
Use latest node-gyp

### PR DESCRIPTION
**Pull request by jeremad**
This gets rid of "python2-only" issues.

We also remove Node < 6 as those versions are not supported anymore. (even node 6 is not maintained)

### CODE REVIEW

**Comment by jeremad** [comment]
I "fixed" the CI by removing older, unmaintained, node versions. Any chance to get a review on this?

**Comment by xzyfer** [comment]
This cannot land of master to the breaking changes. Could you set to PR to be against the v5 branch were it is likely to land.

**Comment by jeremad** [comment]
Thank you!

**Comment by jeremad** [comment]
You actually already did it on the v5 branch. Thank you again.

**Comment by xzyfer** [comment]
Please rebase out all the commits except the package.json changes. You have conflicts now because we've made changes to supported node versions on the v5 branch.

**Comment by xzyfer** [comment]
Great. Thanks for the contribution. We hope to release v5 soon.

**Comment by jeremad** [comment]
Any idea when the v5 will be released?

**Pull request closed without merging**
