### PR TITLE
Use true-case-path to fix re-entrancy issue on Windows

### LINKED ISSUE #1895: Error: Module did not self-register
I'm in the process of upgrading my team's project to webpack 2, and I'm now encountering numerous "Module did not self-register" errors for `.scss` files, both locally and in our build system. Example errors for one file:

```
ERROR in c:/Agents/01/_work/1/s/obj/framework/owa-application/lib/styles/globalstyles.global.scss
Module build failed: ModuleBuildError: Module build failed: Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\Agents\01\_work\1\s\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (C:\Agents\01\_work\1\s\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at C:\Agents\01\_work\1\s\node_modules\webpack\lib\NormalModule.js:141:35
    at C:\Agents\01\_work\1\s\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Agents\01\_work\1\s\node_modules\loader-runner\lib\LoaderRunner.js:170:18
    at loadLoader (C:\Agents\01\_work\1\s\node_modules\loader-runner\lib\loadLoader.js:27:11)
    at iteratePitchingLoaders (C:\Agents\01\_work\1\s\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Agents\01\_work\1\s\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Agents\01\_work\1\s\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\Agents\01\_work\1\s\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Agents\01\_work\1\s\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Agents\01\_work\1\s\node_modules\loader-runner\lib\LoaderRunner.js:165:10)

ERROR in C:\Agents\01\_work\1\s\node_modules\extract-text-webpack-plugin\loader.js??ref--1-0!C:\Agents\01\_work\1\s\node_modules\style-loader\index.js!C:\Agents\01\_work\1\s\node_modules\css-loader\index.js?minimize!C:\Agents\01\_work\1\s\node_modules\postcss-loader\index.js??ref--1-3!C:\Agents\01\_work\1\s\node_modules\sass-loader\lib\loader.js!c:\Agents\01\_work\1\s\obj\framework\owa-application\lib\styles\globalstyles.global.scss doesn't export content

ERROR in C:\Agents\01\_work\1\s\node_modules\extract-text-webpack-plugin\loader.js??ref--1-0!C:\Agents\01\_work\1\s\node_modules\style-loader\index.js!C:\Agents\01\_work\1\s\node_modules\css-loader\index.js?minimize!C:\Agents\01\_work\1\s\node_modules\postcss-loader\index.js??ref--1-3!C:\Agents\01\_work\1\s\node_modules\sass-loader\lib\loader.js!c:\Agents\01\_work\1\s\obj\framework\owa-application\lib\styles\globalstyles.global.scss doesn't export content

ERROR in C:\Agents\01\_work\1\s\node_modules\extract-text-webpack-plugin\loader.js??ref--1-0!C:\Agents\01\_work\1\s\node_modules\style-loader\index.js!C:\Agents\01\_work\1\s\node_modules\css-loader\index.js?minimize!C:\Agents\01\_work\1\s\node_modules\postcss-loader\index.js??ref--1-3!C:\Agents\01\_work\1\s\node_modules\sass-loader\lib\loader.js!c:\Agents\01\_work\1\s\obj\framework\owa-application\lib\styles\globalstyles.global.scss doesn't export content

ERROR in C:\Agents\01\_work\1\s\node_modules\extract-text-webpack-plugin\loader.js??ref--1-0!C:\Agents\01\_work\1\s\node_modules\style-loader\index.js!C:\Agents\01\_work\1\s\node_modules\css-loader\index.js?minimize!C:\Agents\01\_work\1\s\node_modules\postcss-loader\index.js??ref--1-3!C:\Agents\01\_work\1\s\node_modules\sass-loader\lib\loader.js!c:\Agents\01\_work\1\s\obj\framework\owa-application\lib\styles\globalstyles.global.scss doesn't export content
    
Child extract-text-webpack-plugin:
ERROR in ./~/css-loader?minimize!./~/postcss-loader?{"plugins":[null,null]}!./~/sass-loader/lib/loader.js!c:/Agents/01/_work/1/s/obj/framework/owa-application/lib/styles/globalstyles.global.scss
    Module build failed: Error: Module did not self-register.
        at Error (native)
        at Object.Module._extensions..node (module.js:597:18)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at module.exports (C:\Agents\01\_work\1\s\node_modules\node-sass\lib\binding.js:19:10)
        at Object.<anonymous> (C:\Agents\01\_work\1\s\node_modules\node-sass\lib\index.js:14:35)
        at Module._compile (module.js:570:32)
```

When I search for the error, I find issues opened ~2 years ago that have all allegedly been fixed since, but nothing more recently. I've followed the Troubleshooting guide, and tried such suggestions as doing a clean `npm install` (which our build system does anyway) and running `npm rebuild`, to no avail.

- NPM version (`npm -v`): `3.10.10`
- Node version (`node -v`): `v6.9.5`
- Node Process (`node -p process.versions`): 
```
    { http_parser: '2.7.0',
      node: '6.9.5',
      v8: '5.1.281.89',
      uv: '1.9.1',
      zlib: '1.2.8',
      ares: '1.10.1-DEV',
      icu: '57.1',
      modules: '48',
      openssl: '1.0.2k' }
```
- Node Platform (`node -p process.platform`): `win32`
- Node architecture (`node -p process.arch`): `x64`
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass       4.5.0   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`): `node-sass@4.5.0`

### PR DESCRIPTION
**Pull request by MLoughry**
Fixes #1895 

When using node-sass through multiple entry points (as can happen when using webpack) on Windows, the casing of the drive letter in the path can be inconsistent. Since Node is case-sensitive to a fault, this results in Node attempting to create a second instance of the native binding, which results in a `Module did not self-register` error.

The fix is to use `true-case-path` to normalize the binding path, to prevent unintended duplicate bindings from occurring.

### CODE REVIEW

**Comment by xzyfer** [comment]
Please remove the `package-lock.json`

**Comment by MLoughry** [comment]
`package-lock.json` is generated automatically by npm 5, so I've also added it to `.gitignore`

**Comment by xzyfer** [comment]
Thanks!

**Comment by MLoughry** [comment]
No problem. Is there a timeline for the next patch release? Currently this bug is blocking some development on my team.

**Comment by nealoke** [comment]
@MLoughry  +1 for this annoying issue :)

**Comment by xzyfer** [comment]
Best estimate is some time this week

**Pull request merged**
