### PR TITLE
[v5]Use ES2015 template strings instead of string concatenation.

### PR DESCRIPTION
**Pull request by realityking**
I think template strings are one of the biggest readability wins of ES2015 and also perfectly supported in Node.js 4.

Relates to #2312

### CODE REVIEW

**Comment by realityking** [comment]
I think the `v5` branch was rebased at some point. I've updated this PR to account for that.

**Comment by realityking** [comment]
@xzyfer Any feedback on this PR?

**Comment by xzyfer** [comment]
Sorry I'm in a European vacation for a couple months. I'll check in on
things when I have my laptop and wifi

**Comment by realityking** [comment]
Rebased for the current `v5` branch

**Comment by PolyPik** [comment]
You better rebase your fork as there are recent changes to v5.

**Comment by xzyfer** [comment]
Thanks for your efforts. We're happy to move forward without this change as it change for changes sake.

**Pull request closed without merging**
