### PR TITLE
Update spec runner for full sass-spec coverage

### PR DESCRIPTION
**Pull request by nschonni**
- Update the spec runner from work in sass-spec
- Bump sass-spec tag to 3.3.6

### CODE REVIEW

**Comment by nschonni** [comment]
OK, I've rebase the commits. I think it's ready for review/landing now

**Comment by xzyfer** [comment]
Nice one. I'm too fussed with specifics of the implementation as long as it works. If you're happy with it :ship:

**Comment by xzyfer** [comment]
Related https://github.com/sass/node-sass/pull/1705

**Comment by xzyfer** [comment]
Nice one. I had originally cherry-picked this PR into mine. I figured there was value in having them separate incase mine needed to be reverted. :ship:

**Comment by nschonni** [comment]
Yeah, I wanted to make sure they worked together

**Comment by nschonni** [comment]
Think I need to add back in the path replacements for Windows. I'll take a look tomorrow

**Comment by nschonni** [comment]
Think this should fix the wall of Windows errors, but I'm not getting this
```console
  1) cli node-sass sass/ --output css/ should not error if output directory is a symlink:
     Error: EEXIST: file already exists, mkdir 'C:\Workspaces\node-sass\test\fixtures\input-directory\css'
      at Error (native)
      at Object.fs.mkdirSync (fs.js:794:18)
      at Context.<anonymous> (C:\Workspaces\node-sass\test\cli.js:582:10)
      at callFnAsync (C:\Workspaces\node-sass\node_modules\mocha\lib\runnable.js:349:8)
      at Test.Runnable.run (C:\Workspaces\node-sass\node_modules\mocha\lib\runnable.js:301:7)
      at Runner.runTest (C:\Workspaces\node-sass\node_modules\mocha\lib\runner.js:422:10)
      at C:\Workspaces\node-sass\node_modules\mocha\lib\runner.js:528:12
      at next (C:\Workspaces\node-sass\node_modules\mocha\lib\runner.js:342:14)
      at C:\Workspaces\node-sass\node_modules\mocha\lib\runner.js:352:7
      at next (C:\Workspaces\node-sass\node_modules\mocha\lib\runner.js:284:14)
      at Immediate._onImmediate (C:\Workspaces\node-sass\node_modules\mocha\lib\runner.js:320:5)

  2) cli node-sass --follow --output output-dir input-dir should compile with the --follow option:
     Error: EEXIST: file already exists, mkdir 'C:\Workspaces\node-sass\test\fixtures\follow\input-dir'
      at Error (native)
      at Object.fs.mkdirSync (fs.js:794:18)
      at Context.<anonymous> (C:\Workspaces\node-sass\test\cli.js:623:10)
      at callFnAsync (C:\Workspaces\node-sass\node_modules\mocha\lib\runnable.js:349:8)
      at Test.Runnable.run (C:\Workspaces\node-sass\node_modules\mocha\lib\runnable.js:301:7)
      at Runner.runTest (C:\Workspaces\node-sass\node_modules\mocha\lib\runner.js:422:10)
      at C:\Workspaces\node-sass\node_modules\mocha\lib\runner.js:528:12
      at next (C:\Workspaces\node-sass\node_modules\mocha\lib\runner.js:342:14)
      at C:\Workspaces\node-sass\node_modules\mocha\lib\runner.js:352:7
      at next (C:\Workspaces\node-sass\node_modules\mocha\lib\runner.js:284:14)
      at Immediate._onImmediate (C:\Workspaces\node-sass\node_modules\mocha\lib\runner.js:320:5)
```
But I may just have something broken somehow when I reset my branch. Appveyor will tell the truth

**Comment by xzyfer** [comment]
@nschonni I believe this is because our tests have side effects i.e. creating files on disk. Not all the tests clean up after themselves. So running tests after a failed run could end up with created files having not been removed.

We need to address this because it can cause issues with the `retry` added for the timeouts in CI.

**Comment by nschonni** [comment]
I'll see if I can find out what needs to change in the before/after test to see what might need cleaning up

**Pull request merged**
