### PR TITLE
Upgrade vulnerable dependencies

### PR DESCRIPTION
**Pull request by traviisd**
Upgrading vulnerable dependencies per npm audit suggestions. 

https://docs.npmjs.com/getting-started/running-a-security-audit

This is my first contribution for this project and would like any feedback concerns with this change since there are many here that have deep knowledge of this codebase. I compared the test runs, builds, coverage, linting before and after the upgrades. The potential breaking changes are the dev-dependencies coveralls & mocha. 

Most are related to package hoek used in requests and coveralls: https://nodesecurity.io/advisories/566

Running ```npm audit```

```
=== npm audit security report ===

found 17 vulnerabilities (1 low, 15 moderate, 1 critical) in 1206 scanned packages
  run `npm audit fix` to fix 10 of them.
  7 vulnerabilities require semver-major dependency updates.
```

Auto fixed 10 packages
```
npm audit fix
+ request@2.87.0
added 15 packages from 18 contributors, removed 5 packages and updated 9 packages in 2.776s
fixed 10 of 17 vulnerabilities in 1206 scanned packages
  2 package updates for 7 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or do it by hand)
```

Potential breaking changes in 2 packages
```
npm audit

=== npm audit security report ===

npm install --save-dev coveralls@3.0.1  to resolve 5 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change

npm install --save-dev mocha@5.2.0  to resolve 2 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change

critical within mocha https://nodesecurity.io/advisories/146
```

After manual upgrades of coveralls and mocha
```
=== npm audit security report ===

found 0 vulnerabilities
 in 1142 scanned packages
```

Tests (same before and after)
```
6101 passing (22s)
580 pending
```

### CODE REVIEW

**Comment by nschonni** [comment]
Sorry, our pull request template asks people not to bump `request` it's a known issue.

**Comment by traviisd** [comment]
sorry about that

**Comment by arabold** [comment]
I must admit that I'm confused by the last comment. Does this mean there's no intention to address the audit reports in `node-sass`? The `request` module would need to be updated to address those.

**Comment by xzyfer** [comment]
Please search and read through the dozens of identical issues. This has
been thoroughly covered countless times.

**Comment by arabold** [comment]
Yes, there are dozens of PRs and bug reports. My confusion is/was due to most PRs being closed with a "do not bump `request`" statement without further explanation. It only becomes obvious when you actually try to report a bug yourself, not when reading through the top +/- 5 bugs filed about this issue.

Sorry about that. Just a suggestion to maybe change the standard reply of these reports to something like that: 

> This is a known issue and will be addressed in `node-sass` 5.0.0. Unfortunately at this time we do not have a projected release date.

This way somebody that goes through the bug reports will have an easier time to understand what's happening 🙄

Thanks 👋

**Comment by axelson** [comment]
This will be fixed in v5. Tracking issue: https://github.com/sass/node-sass/issues/2355

**Pull request closed without merging**
