### PR TITLE
require request 2.85.1

### PR DESCRIPTION
**Pull request by paulschreiber**
request 2.85.1 requires hawk 6.0.2, which requires boom 4.x.x, which requires hoek 4.x.x. (hoek 2.16.3 has a security vulnerability).

### CODE REVIEW

**Comment by paulschreiber** [comment]
If you don't want to use current `request`, how do you propose getting a current hoek? How will you address #2355?

**Comment by xzyfer** [comment]
Please respect our time by search for issues before opening a new one. Your questions have all been answered many times.

**Comment by paulschreiber** [comment]
I see from #2288 that this has been known for at least six weeks. Sigh.

**Comment by xzyfer** [comment]
It's know and unpatched on purpose because request broke semver by dropping
node < 4 support.

**Comment by YasharF** [comment]
For anyone that is looking at this issue, the dependency upgrade is in the works with the release of node-sass 5.  See https://github.com/sass/node-sass/pull/2312

**Pull request closed without merging**
