### PR TITLE
Additional tests for SassTypes::Color

### PR DESCRIPTION
**Pull request by saper**
A byproduct of #1054

### CODE REVIEW

**Comment by xzyfer** [comment]
Ship when ready! :tada:

**Comment by saper** [comment]
> Ship when ready! :tada:

Not sure I like the indented layout of output. Opinions?

We need moar of these! List! Maps! Crazy constructors!

If I do conversion in the binding code, 
"new sass.types.Boolean('string')" brings false,
if I do casting - it errors. I think the latter is better?

**Comment by xzyfer** [comment]
>Not sure I like the indented layout of output. Opinions?

I don't have my dev laptop with me atm. 

However generally speaking I care about the layout of the test themselves with regards to readability (which I think is perfectly fine). IMHO the output doesn't matter since you only care about the tests that fail :)

**Comment by xzyfer** [comment]
>If I do conversion in the binding code,
>"new sass.types.Boolean('string')" brings false,
>if I do casting - it errors. I think the latter is better?

I'm not following. Does this relate directly to this PR. I'd rather we didn't change the implementation of the Sass types atm.

**Comment by saper** [comment]
> >If I do conversion in the binding code,
> >"new sass.types.Boolean('string')" brings false,
> >if I do casting - it errors. I think the latter is better?
> 
> I'm not following. Does this relate directly to this PR. I'd rather we didn't change the implementation of the Sass types atm.

Good, I'll keep that in mind! Once I figure out how it works :>

**Pull request merged**
