### PR TITLE
Bump libsass to 3.5.0.beta.3

### LINKED ISSUE #1854: AVX extensions required for bindings on win32-x64
Installing node-sass via npm install on Windows Server 2012:

`npm install node-sass`

downloads a native bindings library for win32-x64. This library, when node-sass is run on a box that does not have AVX enabled, exits with a STATUS_ILLEGAL_INSTRUCTION (0xC000001D). Is it possible to have a different version (compiled without AVX instructions) of the bindings installed if the platform does not support them?

System information:
>npm -v
3.10.10
>node -v
v6.9.3
>node -p process.versions
{ http_parser: '2.7.0',
  node: '6.9.3',
  v8: '5.1.281.89',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' }
>node -p process.platform
win32
>node -p process.arch
x64
>node -p "require('node-sass').info"
node-sass       4.2.0   (Wrapper)       [JavaScript]
libsass         3.4.3   (Sass Compiler) [C/C++]
>npm ls node-sass
`-- node-sass@4.2.0

### LINKED ISSUE #1880: Segfault calling `simple-selectors()`
`simple-selectors('&:hover')` causes a segfault.

In ruby Sass it gives an error:

```
Error: $selector: "&:hover" is not a valid selector: Invalid CSS after "": expected selector, was "&:hover" for `simple-selectors'
        on line 1 of standard input
```

### LINKED ISSUE #1904: index variable reference issues in for loops within functions
I was wondering why we use a beta version of libsass. Mainly because its the only version that has [index variable reference issues in for loops within functions](https://github.com/sass/libsass/issues/2330) issue, that causes some problems on multiple projects that I maintain. A library that I wrote depends on this.

Let me know if I should also post the whole issue here.

- NPM version (`npm -v`): 4.2.0
- Node version (`node -v`): v7.5.0
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '7.5.0',
  v8: '5.4.500.48',
  uv: '1.10.2',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
``` 
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass	4.5.0	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```
- npm node-sass versions (`npm ls node-sass`):
```
└─┬ gulp-sass@3.1.0
  └── node-sass@4.5.0
```

When encountering a syntax, or compilation issue:

- [Open issue on `LibSass`](https://github.com/sass/libsass/issues/2330).

### LINKED ISSUE #1935: Error: Undefined operation in multiplication
We're having the following issue: https://github.com/sass/libsass/issues/2309 This has been fixed by the following release of libsass: https://github.com/sass/libsass/releases/tag/3.5.0.beta.3. Is there a possibility that libsass could be bumped to this version?

Thanks in advance! :)

### LINKED ISSUE #2144: calc() is being evaluated and the result is being outputted to CSS instead of the calc() function being outputted to CSS
- NPM version (`npm -v`): 3.10.10
- Node version (`node -v`): 6.12.0
- Node Process (`node -p process.versions`): { http_parser: '2.7.0',
  node: '6.12.0',
  v8: '5.1.281.108',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2m' }
- Node Platform (`node -p process.platform`): orm
darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): node-sass	3.13.1	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]
- npm node-sass versions (`npm ls node-sass`): 3.13.1

We have a Sass function and mixin that responsively changes the font size based on viewport width. It does this by calculating a constant rate of change and then outputting a calc() value that is essentially calc(Xvw + Yrem). The key is that the css is a calc() with the vw in it so that it can constantly be evaluating the font size based on the viewport width and changing accordingly. Our function worked great when we were using node v4.2.2 (npm v3.8.6) but not on node version 6 or 7. Instead, the calc() will be evaluated and then a static value will be outputted to the stylesheet (say font-size: 4.25rem; instead of the desired font-size: calc(1.4vw + 2.64rem); or whatever). 

I would expect the calc() to be outputted to the stylesheet instead of being evaluated and then the result being outputted.

### PR DESCRIPTION
**Pull request by saper**
Supersedes #1908
Fixes #1854
Fixes #1880
Fixes #1904
Fixes #1935 
Fixes #2144

### CODE REVIEW

**Comment by RDeluxe** [comment]
Sorry, when this will be merged in master ? Thanks !

**Comment by danez** [comment]
Also looking forward to this.

**Comment by saper** [comment]
Yes, I am looking forward to this. I made a mistake thinking that 3.4.6 is something we want to use, but then I realized it's 3.4 release series and I just rebased this one. I have marked bugs in [the milestone](https://github.com/sass/node-sass/milestone/32) that might be fixed by the 3.5.0 update, probably not all of them. 

When you are ready, I am happy to update this one.

**Comment by reppners** [comment]
Are the fixes that are included in the latest releases of 3.4.x also in the 3.5.0-beta releases? My team needs the long-path fix for windows contained in 3.4.7 but it seems that we can't get those with 3.5.0-betas. Is it possible to point node-sass to a certain binary?

**Comment by danez** [comment]
Any news on this?

**Comment by saper** [comment]
https://github.com/sass/node-sass/pull/2269 is a long awaited update. Thanks @xzyfer! 🎉

**Comment by JonAtOlo** [comment]
^^ agreed!
is there a planned release for #2269 ?

**Comment by xzyfer** [comment]
Yes soon. We're investigating whether we can mitigate #2023 Inna reasonable
amount of time.

On 9 Mar. 2018 5:49 am, "JonAtOlo" <notifications@github.com> wrote:

^^ agreed!
is there a planned release for #2269
<https://github.com/sass/node-sass/pull/2269> ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sass/node-sass/pull/2071#issuecomment-371584926>, or mute
the thread

**Comment by jcampbell05** [comment]
Is there a workaround for this in the meantime ? this breaks foundation.css for me when using gulp-sass

**Comment by xzyfer** [comment]
4.8.2 has the latest LibSass

**Pull request closed without merging**
