### PR TITLE
Rebase v5 on top of e1fc1580c2e979113c95850b8ae5d83845063ca5

### LINKED ISSUE #2906: Rebase branch v5 on master
Rebase branch v5 on commit aa193f6

### PR DESCRIPTION
**Pull request by saper**
Rebase v5 branch on top of the now-current master (fixes #2906 from @PolyPik)

### CODE REVIEW

**Comment by PolyPik** [comment]
Wouldn't it be simpler to have someone with write permissions to this repository to do a rebase on a local repository then push those changes back into this one?

**Comment by bricss** [comment]
Is there any updates on this? 😶

**Comment by bricss** [comment]
Still no-signal? ☹️

**Comment by KannarFr** [comment]
@nschonni can you give feedback about this?

**Comment by xzyfer** [comment]
Closing as stale.

**Pull request closed without merging**
