### PR TITLE
API: Provides support for array of importers

### PR DESCRIPTION
**Pull request by am11**
* In order to skip the importer, user must
  return `sass.types.NULL` (or the shorter
  alias `sass.NULL`).
* See the added test on usage.
* Backward compatible: part of me want still
  wants to make it non-backward compatible
  because:
  * We can: in major version v3.0.
  * It will keep the API clean.
  * It will keep the docs clear: type of
    `options.importers` is array of functions.
* Updates docs.

Issue URL: #821.

### CODE REVIEW

**Comment by am11** [comment]
@mgreter, @xzyfer, PTAL.

Also, thoughts on that breaking change note?

**Comment by am11** [comment]
@mgreter, going by perl-libsass and [C-API documentation](https://github.com/sass/libsass/wiki/API-Sass-Importer#return-imports), what is the purpose of last parameter `srcmap`?

**Comment by mgreter** [comment]
@am11 if the loaded content has a sourcemap accociates, you should return the content of the sourcemap in that variable. We don't do anything with it yet, but in the future libsass should remap the resulting css to the provided source-map if possible.

**Comment by am11** [comment]
@mgreter, perfect! I will expose that feature to node-sass API in this PR then. :)

**Comment by mgreter** [comment]
@am11 any ETA when you will release the next beta, so libsass can do another beta round too?

**Comment by am11** [comment]
@mgreter, I am almost ready. Can you please release a beta with the `Sass_Compiler` fixes, so our submodule points to libsass release, instead of some random commit hash? I will wind up the two open PRs soon and publish the next beta.

**Comment by mgreter** [comment]
@am11 lets move that discussion to https://github.com/sass/libsass/issues/1020 :wink:

**Comment by am11** [comment]
I have added the `srcmap` but lets keep it undocumented, since it doesn't have any effect on generated source-map.

I will do the final rebase once libsass next rc/beta is released..

**Pull request merged**
