### PR TITLE
Install: Use npmconf to get proxy config

### PR DESCRIPTION
**Pull request by am11**
//cc @kevva

### CODE REVIEW

**Comment by am11** [comment]
@kevva, so does it LGTY? :)

**Comment by kevva** [comment]
:+1:

**Comment by am11** [comment]
@kevva is `@api` a legal jsdoc block type (identifier)? I could not find that one on http://usejsdoc.org/.

On that note, I think we need `@returns` across the board. :)

**Comment by kevva** [comment]
@am11, I think it's http://usejsdoc.org/tags-access.html but I've always used `@api` for some reason.

**Comment by am11** [comment]
Perhaps we can submit a proposal somewhere for `@access [private / public / protected / internal]` :)

Or even better:  `@scope [private / public / protected / internal]`

**Pull request merged**
