### PR TITLE
Add a hint for Chinese installers

### PR DESCRIPTION
**Pull request by pmq20**
Fix dlmanning/gulp-sass#342

### CODE REVIEW

**Comment by saper** [comment]
Is the proxy mandatory? Why is this problem popping out?

**Comment by pmq20** [comment]
@saper The Internet censorship causes a lot of websites abroad inaccessible, this one included.

**Comment by saper** [comment]
@pmq20 I have re-worded it a bit (it's not only for China, also for many Western corporations) in https://github.com/pmq20/node-sass/pull/1 - I hope you like it this way!

**Comment by pmq20** [comment]
@saper I like it, thanks!

**Pull request merged**
