### PR TITLE
Replace "request" by "got"

### PR DESCRIPTION
**Pull request by zckrs**
* Less dependency
* Use only stream

I use [got@5](https://github.com/sindresorhus/got/tree/v5.x) because node-sass support NodeJS 0.10 and 0.12.

/cc @sindresorhus 

Graph deps compare [Request Graph](http://npm.anvaka.com/#/view/2d/request) vs [Got Graph](http://npm.anvaka.com/#/view/2d/got)

### CODE REVIEW

**Comment by xzyfer** [comment]
I'm not thrilled about being pinned to an older version a library, although it does appear to still be receiving update. NodeJS < 4 support is not going away time soon. Our most used version is 0.12.

**Comment by sindresorhus** [comment]
// @floatdrop

**Comment by floatdrop** [comment]
@xzyfer `got` 5.x will receive updates until Node.JS 0.10 is deprecated.

lgtm.

**Comment by xzyfer** [comment]
Thanks for the clarification @floatdrop

**Comment by xzyfer** [comment]
We need to revert this because need to support proxies. I didn't realise proxies weren't supported at the time, my mistake.

**Comment by zckrs** [comment]
Sorry about that but got doesn't support proxy @sindresorhus?

**Comment by sindresorhus** [comment]
[Not yet built-in](https://github.com/sindresorhus/got/issues/79), but you can easily add it: https://github.com/sindresorhus/got#proxies

**Comment by xzyfer** [comment]
tunnel current has [failing tests] for node 0.10 and 0.12 which are important to us. It may still work but this doesn't inspire confidence and users are currently experiencing issues.

**Pull request merged**
