### PR TITLE
Disable all tests with --watch

### PR DESCRIPTION
**Pull request by saper**
Testing cli this way is completely
unreliable. A new method of testing
is needed.

### CODE REVIEW

**Comment by xzyfer** [comment]
:+1:

**Comment by xzyfer** [comment]
Looks like you missed one?

```
 1) cli "before all" hook for "should return a correct version info":
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (C:\projects\node-sass\node_modules\mocha\lib\runnable.js:189:19)
```

**Comment by saper** [comment]
Looks like node 5.x has watching broken on my favourite OS https://github.com/nodejs/node/issues/3541

**Comment by saper** [comment]
this before all hook checking libsass version must be rewritten in an async way. Will fix of course.

**Comment by xzyfer** [comment]
I believe this has been done.

**Pull request closed without merging**
