### PR TITLE
Update lodash and remove prototype vulnerabilities

### PR DESCRIPTION
**Pull request by cheesestringer**
Fixes: https://github.com/sass/node-sass/issues/2574 by removing prototype vulnerabilities for:

https://ossindex.sonatype.org/component/pkg:npm/lodash.assign

https://ossindex.sonatype.org/component/pkg:npm/lodash.clonedeep

https://ossindex.sonatype.org/component/pkg:npm/lodash.mergewith

### CODE REVIEW

**Comment by nschonni** [comment]
I don't believe this is needed https://github.com/sass/node-sass/issues/2574#issuecomment-450935246

**Comment by cheesestringer** [comment]
There is nothing to update to since these were separate packages. Since then it looks like it has gone back to a single package you import from.

https://www.npmjs.com/package/lodash.assign (2 years old)
https://www.npmjs.com/package/lodash.clonedeep (2 years old)
https://www.npmjs.com/package/lodash.mergewith (almost 2 years old)

**Comment by xzyfer** [comment]
Weird this didn't build in Travis

**Comment by nschonni** [comment]
@xzyfer may be related to this https://developer.github.com/changes/2018-04-25-github-services-deprecation/
We still have the "old" integration setup, so you might need to add the "app" version instead. Might be the same for AppVeyor that also didn't trigger

**Comment by xzyfer** [comment]
We can't migrate just yet
>The following repositories cannot be migrated to travis-ci.com at this time because they are currently active on our legacy platform travis-ci.org. This feature will be available shortly. [Please read our docs on open source migration to learn more](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg). 

I think it was just a dodgy webhook. Please try to rebase on master to kick off a new one.

**Comment by xzyfer** [comment]
Travis CI is now running but failing due to lodash dependencies. Please investigate.

**Comment by stof** [comment]
is there any ETA for a release including that change ?

**Pull request merged**
