### PR TITLE
Misc. Fixes

### PR DESCRIPTION
**Pull request by am11**
* README: Removes v0.11 workaround section
  * Reason: njs v0.11 is not relavent any more.
  * Solution: Update to node v0.12 with which<br />
                  node-sass v2.0.1 is compatible OOTB.

* CI: Updates io.js to 1.2 for AppVeyor.

* Code: Throws `Error` object.
  * Returns json-string error from LibSass as is.
  * Extends empty error object with parsed JSON.<br/>
  Note: The reason why [`NanError`](https://github.com/rvagg/nan#nanerrormessage-nantypeerrormessage-nanrangeerrormessage) is not used<br />because LibSass returns error as JSON<br /> string with `message` as member, so we would<br/> have to reparse and reassign the obj in that case.<br/>Issue URL: #675.

* README: Updates error info. (related to previous commit)

* Code: Uses more C++ style nomenclature. 

* Code: Resolves symbolic link.  <br/>On Windows, process.execPath does not
get resolved symlink path. This commit
fixes the issue.<br/>Related Issue: iojs/io.js#851.

### CODE REVIEW

**Comment by kevva** [comment]
Good stuff lately @am11! This look good to me.

**Comment by am11** [comment]
Thanks for the feedback @kevva. :)

**Comment by am11** [comment]
@xzyfer, PTAL.

Note: It does not fix the AppVeyor issue with iojs v1.2 because they are not redirecting node --> iojs when iojs is an active runtime, but they are instead having a concrete node.exe with v1.2 which possesses wrong proc info. Probably they will fix it with the way nvmw handle it: https://github.com/appveyor/ci/issues/139#issuecomment-74421338. Otherwise, we will have to induce that cmd via appveyor.yaml (while deleting node.exe from iojs directory).

**Comment by xzyfer** [comment]
Nothing jumps out at me :+1:

**Pull request merged**
