### PR TITLE
Readme:  Fix the broken anchor

### PR DESCRIPTION
**Pull request by ajhsu**
Fix the link target of the anchor of `functions section`.

### CODE REVIEW

**Comment by nschonni** [comment]
Thanks! The build issues are unrelated so I'll merge this

**Comment by ajhsu** [comment]
Yeah, I got confused when digging into the build issue for an hour.

**Comment by nschonni** [comment]
@ajhsu sorry about that ☹️ , for reference the issue is #2100

**Comment by ajhsu** [comment]
@nschonni It's good to know whats going on, thanks for your fast response!

**Pull request merged**
