### PR TITLE
Update CI builds for NodeJS 6

### PR DESCRIPTION
**Pull request by nschonni**
### Blocked

- [ ] appveyor/ci#770

### CODE REVIEW

**Comment by xzyfer** [comment]
Thanks. This will currently fail hard.

On 4/27/16, Nick Schonning <notifications@github.com> wrote:
>
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/sass/node-sass/pull/1486
>
> -- Commit Summary --
>
>   * Update CI builds for NodeJS 6
>
> -- File Changes --
>
>     M .travis.yml (1)
>     M appveyor.yml (3)
>
> -- Patch Links --
>
> https://github.com/sass/node-sass/pull/1486.patch
> https://github.com/sass/node-sass/pull/1486.diff
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sass/node-sass/pull/1486
>


-- 
Regards,
Michael

**Comment by nschonni** [comment]
Looks like Appveyor is passing because it doesn't understand the `6` version yet. Looking to see why

**Comment by nschonni** [comment]
Looks like AppVeyor will support it shortly https://github.com/appveyor/ci/issues/770

**Comment by xzyfer** [comment]
I think the bigger problem is that node-sass just won't compile with node 6 yet. Every major node release invariably means we need to update the C/C++ binding code.

At the very least we'll need to update NAN.

**Comment by nschonni** [comment]
Yeah, someone pointed out in the other tread that NAN is still trying to figure out the issues raised by the depreciation messages.

**Comment by xzyfer** [comment]
To my amazement we compile fine on Node 6. I've started building some binaries.

**Comment by iddqdidkfa** [comment]
today arch updated my node and npm rebuild node-sass failed

**Comment by xzyfer** [comment]
@iddqdidkfa please provide the output for the following commands

```
npm -v              
node -v
node -p process.versions
node -p process.platform
node -p process.arch
```

**Comment by iddqdidkfa** [comment]
@xzyfer 
```
npm -v
3.8.7

node -v
v6.0.0

node -p process.versions
{ http_parser: '2.7.0',
  node: '6.0.0',
  v8: '5.0.71.35',
  uv: '1.9.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2g' }

node -p process.platform
linux

node -p process.arch
x64
```

**Comment by xzyfer** [comment]
@iddqdidkfa which linux distribution are you on?

```
uname -s
```

**Comment by nschonni** [comment]
@iddqdidkfa @xzyfer how is this support issue related to updating the CI information?

**Comment by xzyfer** [comment]
@nschonni it's not but it's easier to not fight the tide.

**Comment by iddqdidkfa** [comment]
@xzyfer I'm using Antergos x64
```
uname -s
Linux

uname -a
Linux exec-work 4.5.1-1-ARCH #1 SMP PREEMPT Thu Apr 14 19:19:32 CEST 2016 x86_64 GNU/Linux
```

@nschonni Ok, sorry, no more issues.

**Comment by xzyfer** [comment]
@iddqdidkfa I've never heard of Antergos. We don't officially support your OS. Do you know if previous versions of node-sass worked?

**Comment by iddqdidkfa** [comment]
@xzyfer Antegros is Arch Linux with user friendly installer. I promissed to not discuss this issue here, so created #1493

**Comment by xzyfer** [comment]
@nschonni please update this to match the changes to `.travis.yml` in #1500.

**Comment by nschonni** [comment]
Rebased

**Comment by xzyfer** [comment]
Thanks. This is final blocker for 3.7.0.

**Comment by nschonni** [comment]
Realized that the AppVeyor config was spit between the tag and master builds. I added 6 to the master section and repushed

**Comment by roc** [comment]
Can't wait for `3.7.0`!  :-)

**Comment by xzyfer** [comment]
Looks like node 6 has shipped on appveyor. We have a failing test on node 7 Windows. Will take a closer look tomorrow. It looks race conditiony.

**Comment by saper** [comment]
I wonder if this didn't get solved in https://github.com/nodejs/node/pull/5950 , after v6.0 release.

**Comment by xzyfer** [comment]
@saper I want to ahead an ship 3.7.0 with the debug files, which means we don't need to subst. We can retroactively add the debug files when/if https://github.com/nodejs/node/issues/6500 is suitably resolved.

**Comment by xzyfer** [comment]
Superseded by #1517 because of timezones.

**Pull request closed without merging**
