### PR TITLE
Fix 'unreadable file error' in watch mode after a save in vscode

### PR DESCRIPTION
**Pull request by marcosbozzani**
This fix detects 'File to read not found or unreadable' and 'File to import not found or unreadable' errors that occasionally happens after a file save in Visual Studio Code when node-sass is running on watch mode.

If those errors are detected, a retry mechanism is applied. It verifies that the file actually exists and limits the maximum number of retries to 1000. In my local tests, it usually takes less than 5 retries. The limit is there as a safety measure to prevent infinite recursion and the value is high enough for those cases where the machine is really slow or it has to access a storage with high latency, like a remote one.

Those errors happen with 'node-sass (watch mode)', 'chokidar + node-sass' and 'node-sass-chokidar (watch mode)' too.

It is also possible to change the retry mechanism for one with exponential backoff. For example:

Change this code:
```js
if (isFileUnreadable(error) && retries < 1000) {
      retries++;
      sass.render(renderOptions, renderCallback);
}
```

For this one:
```js
if (isFileUnreadable(error) && retries < 4) {
      retries++;
      setTimeout(() => sass.render(renderOptions, renderCallback), Math.pow(retries, 5));
}
```

Related issues:
https://github.com/sass/node-sass/issues/1894
https://github.com/sass/node-sass/issues/2022
https://github.com/Microsoft/vscode/issues/20491
https://github.com/facebook/create-react-app/issues/2531
https://github.com/michaelwayman/node-sass-chokidar/issues/14
https://github.com/michaelwayman/node-sass-chokidar/issues/22
https://stackoverflow.com/questions/50395998/vscode-wont-work-with-filewatchers

### CODE REVIEW

**Comment by marcosbozzani** [comment]
Sorry if I wasn't clear enough in the PR. I know it's not node-sass fault. Yet this cause a very annoying issue for node-sass users. This could serve as a temporary workaround that could be removed once the real issue was solved. It doesn't affect those editors that do that right thing and mitigate the problem until the other editors can be fixed.

Chokidar fails as well (chokidar + node-sass and node-sass-chokidar), as you can see in the related issues. :confused:

I'm just sharing the solution that worked for me, so anyone can use it. :wink:

If this is really not the right place for this patch, I'm sorry for the trouble. :sweat_smile:

**Comment by maartenraes** [comment]
@marcosbozzani worked form me by replacing the file localy, many thanks! 👍

**Comment by seradork** [comment]
In my environment it did not work well.
I modified it as follows and it worked.

line 126-129:
```js
    if (unreadable) {
      var dir = path.dirname(error.file);
      var file = error.message.split('not found or unreadable: ')[1].trim().slice(0,-1);
      var fileDir = path.dirname(file);
      var fileName = path.basename(file);
      return (
        fs.existsSync(path.join(dir,fileDir,fileName)) ||
        fs.existsSync(path.join(dir,fileDir,"_" + fileName)) ||
        fs.existsSync(path.join(dir,fileDir,fileName + ".scss")) ||
        fs.existsSync(path.join(dir,fileDir,"_" + fileName + ".scss"))
      );
    }
```

- win7 64bit
- node-sass 4.9.2
- vscode 1.25.1

**Comment by cyberpro4** [comment]
Just leaving here a simple solution found.

Since the problem is a "race condition" between the editor save operation and the watch itself, adding --use-polling option will break the concurrence. For ex:

`node-sass-chokidar src/ -o src/ --watch --recursive --use-polling --polling-interval 1000`

**Comment by Ness70** [comment]
@marcosbozzani, If I may ask, where and in which file do you add this code.

**Comment by ehindola** [comment]
please anybody how do i use this  change the retry mechanism for one with exponential backoff?

**Comment by MattixNow** [comment]
Up ?

**Comment by ayofef** [comment]
where do i paste this line of code:
if (isFileUnreadable(error) && retries < 4) {
      retries++;
      setTimeout(() => sass.render(renderOptions, renderCallback), Math.pow(retries, 5));
}

**Comment by Agasthian** [comment]
@ayofef  you can patch this code in your project's node-sass local 
Location => 'node_modules/node-sass/lib/render.js' 
Line no => 114 in render.js file.
This solution works for me.

**Comment by nschonni** [comment]
You could look at using something like https://www.npmjs.com/package/patch-package to apply patches like this. (Haven't tried, just searched for "npm patches")

**Comment by ayofef** [comment]
Thank you

**Comment by wfabio** [comment]
> @marcosbozzani worked for me by replacing the file localy, many thanks! 👍

Hello Marcos, Can you, please, tell me how to replace this file? I have no idea how to do it.

**Comment by marcosbozzani** [comment]
@wfabio, locate the file `node-sass/lib/render.js` inside your local `node_modules` folder and replace with this code:

https://github.com/marcosbozzani/node-sass/blob/bug-vscode-watch/lib/render.js

You may need to redo this if you reinstall the library with `npm` or `yarn`

**Comment by saper** [comment]
Can somebody explain me what exactly vscode is doing? What is the sequence of operations we are seeing when saving the file?

**Comment by eastlin7** [comment]
I added this to node-sasss and it fixed my issue on my windows 10 machine.

**Comment by saper** [comment]
@maartenraes can you come up with some reasonable value lower than 1000 ?

**Comment by saper** [comment]
Could anyone experiencing this add the following patch to the libsass code (`src/libsass/src/file.cpp`) then rebuild node-sass and see what error message is generated?

```
diff --git a/src/libsass/src/file.cpp b/src/libsass/src/file.cpp
index 32d4a7c63..ead19c947 100644
--- a/src/libsass/src/file.cpp
+++ b/src/libsass/src/file.cpp
@@ -417,7 +417,10 @@ namespace Sass {
         if (rv > 32767) throw Exception::OperationError("Path is too long");
         if (rv == 0) throw Exception::OperationError("Path could not be resolved");
         HANDLE hFile = CreateFileW(resolved, GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, 0, NULL);
-        if (hFile == INVALID_HANDLE_VALUE) return 0;
+        if (hFile == INVALID_HANDLE_VALUE) {
+             std::cerr << "Error opening file:" << resolved << "LastError was [" << GetLastError() << "]" << std::endl; return 0; 
+            return 0;
+        }
         DWORD dwFileLength = GetFileSize(hFile, NULL);
         if (dwFileLength == INVALID_FILE_SIZE) return 0;
         // allocate an extra byte for the null char
```

**Comment by marcosbozzani** [comment]
A ready to use patch equivalent to this PR is available here: https://github.com/marcosbozzani/patch-node-sass-watch

**Pull request closed without merging**
