### PR TITLE
Chore: Add Node 8 to Appveyor

### PR DESCRIPTION
**Pull request by nschonni**
Related to #1985

### CODE REVIEW

**Comment by xzyfer** [comment]
I'm not sure AppVeyor images support Node 8 yet. I know in the past we've have to wait for them add new Node version to their images i.e. https://www.appveyor.com/updates/2017/05/18/

>Node.js 4.8.3, 6.10.3, 7.10.0

https://github.com/appveyor/ci/issues/1581 however supports Node 8 should work, but maybe a bit slow

**Comment by nschonni** [comment]
It seemed to work OK https://ci.appveyor.com/project/sass/node-sass/build/2529/job/367mayw9pmqb2ryj

**Comment by xzyfer** [comment]
Nice one

**Comment by nschonni** [comment]
I have been looking at their NPM install script tonight to see if I can get it to behave like NVM on Travis (``node`, `lts/argon`, etc...)

**Comment by xzyfer** [comment]
It's worth noting that LTS codenames may cease to be a thing - https://github.com/nodejs/LTS/issues/127

**Pull request merged**
