### PR TITLE
Suppress -std=c++0x option

### PR DESCRIPTION
**Pull request by saper**
Followup-to: https://github.com/sass/node-sass/pull/2553

### CODE REVIEW

**Comment by saper** [comment]
As it turns out, we need it for g++47 for node v0.10 and v0.12.

**Comment by xzyfer** [comment]
@saper can you please rebase this on the v5 branch?

**Comment by saper** [comment]
> @saper can you please rebase this on the ~v5~ `next-major` branch?

I guess it did merge without issues?

**Comment by xzyfer** [comment]
Yep all good.

**Pull request merged**
