### PR TITLE
Workaround iojs/io.js#751 Windows iojs.exe alias

### PR DESCRIPTION
**Pull request by saper**

### CODE REVIEW

**Comment by saper** [comment]
I am getting build failures on iojs:

https://gist.github.com/cacacd602e84db9dde72

**Comment by am11** [comment]
@saper, there is a reason we didn't opted for this route. We shouldn't be hardcoding the executable name in the configuration file. It should work with `npm task`.

Wait for io.js to fix this issue on Windows. Meanwhile running tests locally on Windows passes all tests.

**Comment by saper** [comment]
I don't believe iojs will fix iojs/io.js#751 quickly. There is no good solution in sight.

Of course this is an ugly workaround. I'd rather have tests running (somehow, not sure if we can make them run this way). 
Alternatively of course we can remove iojs from the Windows matrix...

What is `npm task`?

**Comment by am11** [comment]
> What is  npm task ?
npm test

**Comment by saper** [comment]
Ah, thanks. Well, changing appveyor script does not break `npm test`....

**Comment by am11** [comment]
We need io.js in the matrix to observe if the binary builds fine, but it is allowed to fail later.
If you want to carry out further experiments, please do it in your fork. 

Sorry, but we are fine waiting for io.js to bring the solution to (which they think is a) trivial issue and so do we.

**Pull request closed without merging**
