### PR TITLE
Add  OpenBSD support

### PR DESCRIPTION
**Pull request by ledeuns**

### CODE REVIEW

**Comment by saper** [comment]
Do you know how and who will be building binaries for OpenBSD?

**Comment by ledeuns** [comment]
There will be no binary for node-sass.
www/sass package is maintained by frantisek holop.
lang/node was maintained by Aaron Bieber.

**Comment by saper** [comment]
We are getting requests like https://github.com/sass/node-sass/issues/2840#issuecomment-624358082 from folk who try to run some apps using node-sass on OpenBSD, please reconsider.

**Comment by frenkel** [comment]
What would be needed to get this merged?

**Comment by anon987654321** [comment]
Please see: https://marc.info/?l=openbsd-ports&m=160657052927238

`ln -s /usr/local/bin/node /tmp/node`

Don't forget to replace `gcc` with `clang`:

```sh
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
```

Shoutout to Solene for the help.

**Pull request closed without merging**
