### PR TITLE
don't pack the test directory into the npm-module

### PR DESCRIPTION
**Pull request by Meir017**
we don't really need the test files in order to use this module 😉

### CODE REVIEW

**Comment by nschonni** [comment]
@xzyfer is this needed for the Canary in the Mine testing by the NodeJS build team?

**Comment by xzyfer** [comment]
Correct. We need to publish tests for https://github.com/nodejs/citgm

**Comment by Meir017** [comment]
Is that module used to run the test in the CI?

**Comment by xzyfer** [comment]
It's a system used by the Node core team to ensure they don't accidentally
break important modules before doing a Node version release.

**Comment by Meir017** [comment]
Hmm, express don't pack their tests https://github.com/expressjs/express/blob/master/package.json#L84

**Pull request closed without merging**
