### PR TITLE
build: Adds win_delay_hook so iojs runs with alias

### PR DESCRIPTION
**Pull request by am11**
Before building, first apply the following patch
to pangyp: rvagg/pangyp#5 (until it is merged).

Issue URL: #870.

### CODE REVIEW

**Comment by xzyfer** [comment]
Hey @am11, do we need to ship this for 3.0.0?

**Comment by am11** [comment]
I think yes as this change has no side effect.
I have changed the pangyp version to my master, until they merge that PR.

**Comment by am11** [comment]
This actually fixes that module registration bug on Windows. :)

**Comment by xzyfer** [comment]
Argh alright. I guess I can revoke the tag since we haven't created the release :) /cc @saper if you figure out what's up with the FreeBSD watcher we can ship it in 3.0.0.

**Comment by saper** [comment]
This change has no effect for us until we inherit objects from v8 or something like that, right?

**Comment by xzyfer** [comment]
I believe it's related to node-sass install script failing with windows on iojs

**Comment by xzyfer** [comment]
This doesn't affect the 3.0.0 node-sass-binaries so I'll ship this and re-tag v3.0.0.

**Pull request merged**
