### PR TITLE
chore: update `request` package

### PR DESCRIPTION
**Pull request by evilebottnawi**
Fix security issues (see https://github.com/request/request/blob/master/CHANGELOG.md#v2810-20170309)

### CODE REVIEW

**Comment by xzyfer** [comment]
This breaks node < 4 support and would be a very big major change for us.
This will happen in version 5.

**Comment by jc1arke** [comment]
Just checking: since this is now being halted on downstream projects by NSP, when will version 5 be released?

Support for Node 4 as an LTS ends in basically 2 months (https://github.com/nodejs/Release#release-schedule), meaning that blocking the dependency update to cater for a soon-to-be-deprecated version just doesn't seem valid.

**Comment by kumorig** [comment]
It should be mentioned that since `npm 6.0.0` anyone who uses node-sass in their project and run `npm install` or `npm update`  gets a big red `[!] 5 vulnerabilities found | Severity: 5 moderate` in their console. I'm not sure of the actual implication of those vulnerabilities, but it *looks* pretty bad from an optics standpoint.

**Comment by tflori** [comment]
just my two cents: node-sass 4.9 requires node-gyp 3.3 and node-gyp 3.3 that also requires hawk 4.2.1 with the result that node-sass 4.9 already requires node >= 4 - so I don't understand the point in blocking an update because it is breaking node 0.10 support :confused:

**Comment by nschonni** [comment]
node-gyp is only used if the binary download fails, which is done through request

**Pull request closed without merging**
