### PR TITLE
Bump libsass

### LINKED ISSUE #1854: AVX extensions required for bindings on win32-x64
Installing node-sass via npm install on Windows Server 2012:

`npm install node-sass`

downloads a native bindings library for win32-x64. This library, when node-sass is run on a box that does not have AVX enabled, exits with a STATUS_ILLEGAL_INSTRUCTION (0xC000001D). Is it possible to have a different version (compiled without AVX instructions) of the bindings installed if the platform does not support them?

System information:
>npm -v
3.10.10
>node -v
v6.9.3
>node -p process.versions
{ http_parser: '2.7.0',
  node: '6.9.3',
  v8: '5.1.281.89',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' }
>node -p process.platform
win32
>node -p process.arch
x64
>node -p "require('node-sass').info"
node-sass       4.2.0   (Wrapper)       [JavaScript]
libsass         3.4.3   (Sass Compiler) [C/C++]
>npm ls node-sass
`-- node-sass@4.2.0

### LINKED ISSUE #1880: Segfault calling `simple-selectors()`
`simple-selectors('&:hover')` causes a segfault.

In ruby Sass it gives an error:

```
Error: $selector: "&:hover" is not a valid selector: Invalid CSS after "": expected selector, was "&:hover" for `simple-selectors'
        on line 1 of standard input
```

### LINKED ISSUE #1904: index variable reference issues in for loops within functions
I was wondering why we use a beta version of libsass. Mainly because its the only version that has [index variable reference issues in for loops within functions](https://github.com/sass/libsass/issues/2330) issue, that causes some problems on multiple projects that I maintain. A library that I wrote depends on this.

Let me know if I should also post the whole issue here.

- NPM version (`npm -v`): 4.2.0
- Node version (`node -v`): v7.5.0
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '7.5.0',
  v8: '5.4.500.48',
  uv: '1.10.2',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
``` 
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass	4.5.0	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```
- npm node-sass versions (`npm ls node-sass`):
```
└─┬ gulp-sass@3.1.0
  └── node-sass@4.5.0
```

When encountering a syntax, or compilation issue:

- [Open issue on `LibSass`](https://github.com/sass/libsass/issues/2330).

### PR DESCRIPTION
**Pull request by xzyfer**
Fixes #1854
Fixes #1880
Fixes #1904

### CODE REVIEW

**Comment by xzyfer** [comment]
CITGM look good

**Comment by nschonni** [comment]
Is it just the binary rebuilds that this is waiting for?

**Comment by xzyfer** [comment]
This will likely be bumped to a newer LibSass version.

**Comment by danez** [comment]
Any idea when this will be ready?

**Comment by elyseholladay** [comment]
We're running into the bug from 1935 — any idea when this might get released? ✨ thank you!

**Comment by agriffis** [comment]
Looking forward to this for working `get-function` in node-sass and therefore bootstrap

**Comment by xzyfer** [comment]
Hello, sorry yes we're working on this. Promise.

get-function won't land until node-sass@5

**Pull request closed without merging**
