### PR TITLE
Do not use C++ exceptions in the binding code

### PR DESCRIPTION
**Pull request by saper**
We are running into trouble with C++ runtime
libraries (notably by mixing libstdc++ and libc++
on MacOSX). Reduce the risk by adhering to Google
Style Guide and stop using C++ exceptions at all.

libsass should offer us a pure C interface
and promises to not throw any exceptions as well.

While here, add additional checks for list and
map values.

Fixes: https://github.com/sass/node-sass/issues/1131
Closes: https://github.com/sass/node-sass/issues/1127

### CODE REVIEW

**Comment by saper** [comment]
@mgol @xzyfer let me know how far are your Macintoshes with this patch.

**Comment by xzyfer** [comment]
>libsass should offer us a pure C interface and promises to not throw any exceptions as well

@saper I believe we're making steps in this direction in 3.3 - https://github.com/sass/libsass/pull/1544

**Comment by saper** [comment]
We don't use `sass_value_op` in node-sass.

**Comment by xzyfer** [comment]
>@xzyfer let me know how far are your Macintoshes with this patch.

943 passing (21s) :100:

**Comment by saper** [comment]
Can you show me your full compiler flags now?

**Comment by xzyfer** [comment]
https://gist.github.com/xzyfer/81e89cee8124f2480c81

**Comment by xzyfer** [comment]
>We don't use sass_value_op in node-sass.

Yep I just meant we agree with the sentiment and we're working on it. Would be worth opening a LibSass issue to track for 3.4.

**Comment by xzyfer** [comment]
:+1: Ship it when you're comfortable @saper

**Pull request merged**
