### PR TITLE
Update libsass to version 3.6.3

### LINKED ISSUE #2685: libsass 3.6.0
https://github.com/sass/libsass/releases/tag/3.6.0

### PR DESCRIPTION
**Pull request by PolyPik**
This PR merges in recent updates to the master branch and updates the libsass version to version 3.6.3.

A pre-test script had to be added and the `spec.js` test file had to be updated to account for the changes in the sass-spec naming and layout style.

Fixes #2685

### CODE REVIEW

**Comment by PolyPik** [comment]
Oh come on.

Could someone here restart that one MacOS build?

**Comment by PolyPik** [comment]
Hey, @saper could you help me restart that one failing Mac build. The other Mac builds went along just fine, so thing else caused that one build to fail.

**Comment by nschonni** [comment]
Done

**Comment by PolyPik** [comment]
Ok it seems the external cause of the failure has not yet been resolved.

We should wait 2 hours and if it still doesn't work then wait until tomorrow.

**Comment by PolyPik** [comment]
Okay, let's try it again.

**Comment by PolyPik** [comment]
Hello? I don't have the permissions to restart the build.

**Comment by xzyfer** [comment]
Done

**Comment by PolyPik** [comment]
Well now, the checks are all green.

@xzyfer Shall we merge it?

**Comment by xzyfer** [comment]
I need to take a look at the changes when I have time

**Comment by xzyfer** [comment]
I've rebased v5 on latest master to help clean up the commits. Are you able to rebase your branch on the latest origin/v5?

**Comment by xzyfer** [comment]
Additionally can you please revert all the changes to sass-spec and the spec runner.

**Comment by PolyPik** [comment]
The spec tests will fail without the changes to the sass-spec version and the changes to `test/spec.js`.

But then again you did mention that node-sass will no longer directly rely on sass-spec. https://github.com/sass/node-sass/pull/2859

**Comment by xzyfer** [comment]
Exactly, I wouldn't expect failures if the sass-spec package version isn't changed in package.json. If there are failures I want to understand them as it'll inform our sass-spec removal strategy.

**Comment by PolyPik** [comment]
@xzyfer 

Somehow when you rebased v5 you lost @L2jLiga 's commit , 3c2d9f6.

But anyways, I did some black magic to get my fork's v5 branch in sync with this v5 branch and to undoing some of the work I put in for the past week or two. Thankfully I managed to save my work to a new branch in case we ever need it.

Oh and the tests in `test/spec.js` will fail.

**Comment by xzyfer** [comment]
I was wondering what that commit was about. I've restored it on v5.

**Comment by xzyfer** [comment]
Thanks for the effort. I'll check in on the CI results in the morning.

**Comment by PolyPik** [comment]
Huh Travis didn't run this time.

Oh well it would've had test failures just the same.

**Comment by DanielNohra** [comment]
please update node-sass to use lib-sass to 3.6.0 I am block since I am using whitesource.
An issue was discovered in LibSass through 3.5.4. An out-of-bounds read of a memory region was found in the function Sass::Prelexer::skip_over_scopes which could be leveraged by an attacker to disclose information or manipulated to read from unmapped memory causing a denial of service.

**Comment by PolyPik** [comment]
@xzyfer What's your assessment on these test failures?

**Comment by xzyfer** [comment]
@PolyPik the failures are exactly what I expected. I've opened a PR to remove sass-spec from v5.

https://github.com/sass/node-sass/pull/2873

Once that is merged please rebase your branch on v5 once again we should be green.

**Comment by PolyPik** [comment]
Okay, so are we ready?

**Comment by xzyfer** [comment]
Thanks!

**Pull request merged**
