### PR TITLE
Create .npmignore to remove 69M tests from package

### PR DESCRIPTION
**Pull request by nodkz**
screen shot 2016-09-06 at 16 18 29

### CODE REVIEW

**Comment by xzyfer** [comment]
Please assume, as a default, that maintainers are smart and well intentioned. 

Then take a moment to understand why something was done [for good reason](https://github.com/sass/node-sass/pull/1688) before [crying foul](https://twitter.com/nodkz/status/773103622678798336). 

Some times it's as easy as reading the [release notes](https://github.com/sass/node-sass/releases/tag/v3.9.0).

We are addressing this issue, but for the time being it has been removed in v3.9.3.

**Comment by nodkz** [comment]
But 69M x 454K downloads on last week = 30 Tb of data. 
I suppose that needs some other solution for providing specs for `citgm`.

PS. Do not mistake the one who does anything. 😉
PSS. I don't want hurt you. And your work is amazing!!! ❤️

**Comment by xzyfer** [comment]
>We are addressing this issue, but for the time being it has been removed in v3.9.3.

If you had followed my suggestion and checked the latest release notes you'd have seen we have addressed this.

**Comment by nodkz** [comment]
Wow, you fixed it 1 hour before I wrote. Awesome.
My fault, I didn't notice this. 
Excuse me again for troubling.

**Comment by xzyfer** [comment]
Can I ask you to please delete your tweets so that people are not confused.

**Comment by nodkz** [comment]
No problem. Done!

**Comment by nodkz** [comment]
BTW firstly I wrote to twitter, cause npmjs.com does not show a link to the git repo. So I found link on twitter here https://www.npmjs.com/package/node-sass 

Right now link to git repo in place.
Npmjs have some [troubles](https://github.com/facebook/relay/issues/1355) with cache last couple of days.

**Comment by xzyfer** [comment]
Thanks.

The github link is in the top right of the npm page. You may also find [this useful](https://twitter.com/addyosmani/status/772834304455942145) for the future.

**Pull request closed without merging**
