### PR TITLE
Add example for basic command-line usage

### PR DESCRIPTION
**Pull request by incompl**

### CODE REVIEW

**Comment by xzyfer** [comment]
Thanks @incompl. I think those docs might be out of date. Have you confirmed that usage examples produces the expected output. 

```

**Comment by incompl** [comment]
`--output` only works for a directory: your example would make a directory called `style.css` in `dest`. I added this new example because I could not figure out how to specify an output filename from the docs, but a coworker showed me that this works. Hence the PR. Hope this helps!

**Comment by incompl** [comment]
Example in action:

    gsmith-retina:temp gsmith$ ls
    gsmith-retina:temp gsmith$ mkdir src
    gsmith-retina:temp gsmith$ touch src/style.scss
    gsmith-retina:temp gsmith$ node-sass src/style.scss dest/style.css
    Rendering Complete, saving .css file...
    Wrote CSS to /Users/gsmith/Code/temp/dest/style.css
    gsmith-retina:temp gsmith$ ls dest
style.css
    gsmith-retina:temp gsmith$

**Comment by xzyfer** [comment]
Great thanks @incompl. Apologies some of this stuff pre-dates me :)

**Pull request merged**
