### PR TITLE
Node 9 support

### PR DESCRIPTION
**Pull request by nschonni**
Related to #2129, but not sure NVM has the tags yet for `carbon`

### CODE REVIEW

**Comment by nschonni** [comment]
Looks like Node 9 isn't available on Appveyor, so I might strip out that commit

**Comment by nschonni** [comment]
Opened https://github.com/appveyor/ci/issues/1895 to track the Appveyor support

**Comment by xzyfer** [comment]
Nice one

**Comment by stefanpenner** [comment]
🤞

**Comment by stefanpenner** [comment]
🕺  looks like we are green, :shipit: !

**Comment by xzyfer** [comment]
That was quick haha

**Pull request merged**
