### PR TITLE
Add sass-webpack-plugin into README

### PR DESCRIPTION
**Pull request by jalkoby**
Hi, node-sass team. There's a tiny layer to join two great tools: libsass & webpack. I didn't add any custom preference or opinion. Just plug and ready to go

### CODE REVIEW

**Comment by xzyfer** [comment]
Thanks. I'll take some time to look into the plugin before we endorse it.

**Comment by jalkoby** [comment]
sure, actually there is an official loader https://github.com/webpack-contrib/sass-loader . But configuration of it makes ages

**Comment by jalkoby** [comment]
any progress yet?

**Comment by xzyfer** [comment]
Sorry for the delay. Thanks for this but we're not going to add any new integrations until we overhaul the documentation. These simply generate too much noise.

**Pull request closed without merging**
