### PR TITLE
chore: Update Istanbul to NYC

### LINKED ISSUE #2664: remove deprecated dependency istanbul
https://www.npmjs.com/package/istanbul this package is already deprecated.

### PR DESCRIPTION
**Pull request by nschonni**
Closes #2664

### CODE REVIEW

**Comment by xzyfer** [comment]
This probably needs to land on v5, or we it use nyc for coverage because old node is not supported.

**Comment by nschonni** [comment]
> This probably needs to land on v5, or we it use nyc for coverage because old node is not supported.

Yup, that makes sense. I didn't check, but I wouldn't be supprised that it broke old Node

**Comment by PolyPik** [comment]
@nschonni 

Is it okay if I opened a PR for merging this commit into the v5 branch instead?

**Comment by nschonni** [comment]
thanks for the ping, i've just tried changing the branch. I'll try a quick rebase to see if resolving this is simple. If the rebase isn't straightforward, i'll ping you to start a new PR

**Pull request merged**
