### PR TITLE
Remove Appveyor in favour of GitHub actions

### PR DESCRIPTION
**Pull request by xzyfer**
Before going too far down this rabbit hole, @nschonni do you think this makes sense?

### CODE REVIEW

**Comment by nschonni** [comment]
I haven't looked in a bit, but Actions didn't have a way of using x86 Node.js before. That's the main reason it's still in the matrix. I think support landed for Azure DevOps, but not sure if Actions caught up yet

**Comment by xzyfer** [comment]
Thanks, that's the context I need  :)

**Comment by nschonni** [comment]
Looks like I started https://github.com/sass/node-sass/pull/3041, but didn't wrap it up. Not sure why anymore

**Comment by xzyfer** [comment]
Might have just been blocked on me missing the review request. Looks like these Windows x86 builds ran which is encouraging.

**Comment by nschonni** [comment]
OK, I'll close this in favour of #3041

**Pull request closed without merging**
