### PR TITLE
Render options in callbacks as this.options

### PR DESCRIPTION
**Pull request by Jakobo**
This patch and tests introduces a context for all callbacks currently
in node-sass. Right now, they run w/ an ambiguous context, making the
`this` keyword not helpful to importer developers (and eventually
custom function developers). This creates a context object, adds the
render options to said context object, and then uses that context for
importer, success, and error callbacks via `this.options`.

By using a context instead of just `.call(options...)` there is a hook
for later should we find additional environmental information is
valuable to importer / custom function developers such as the node
environment, node-sass version, etc.

### CODE REVIEW

**Comment by am11** [comment]
Thanks for the PR. 

Incidentally, does it also fix https://github.com/sass/node-sass/issues/674?

**Comment by am11** [comment]
Also this is related: https://github.com/sass/node-sass/issues/676. And we are targeting that for vNext (2.1).

It may require the change in this functionality again.

**Comment by Jakobo** [comment]
Regarding #674 it would be the options object from `getOptions`, so yes the `this.options.sourceMap` would resolve. 

For #676 I have no problem rebasing this, especially after we add in node style callbacks or promises to the API. I don't really see `getOptions` changing much other than dropping the success/error registration. More than happy to adjust the PR in the next few days.

**Comment by chriseppstein** [comment]
This patch's changes needs to be applied to #644 handling of custom function invocation so that `this.options` works in custom functions as well.

**Comment by Jakobo** [comment]
I agree @chriseppstein. If we can get custom functions rebased, I will include those in the patch as well. 

I'd like to make sure there are no concerns with the scope of our importers and custom functions 
 being an object literal that describes the current render environment. It seems logical without introducing backcompat issues.

**Comment by Jakobo** [comment]
This is now rebased off of #684

**Comment by am11** [comment]
@Jakobo, did you merged your branches by mistake?  It was suppose to have one commit, now there are eight commits. Also CI build is failing. :(

**Comment by Jakobo** [comment]
@am11, I'm sorry, I thought you wanted this rebased off of #684 (rebase is dbf31bac), so it used node style callbacks.

> If you can rebase #681, we can merge it right away.

I will close this and create a new PR based off of HEAD

**Comment by am11** [comment]
@Jakobo, I meant rebase against the node-sass master as there were merge conflicts at the time..

**Comment by Jakobo** [comment]
Ah okay. Then please see #686 which is directly based off of master with `npm test` succeeding locally. Thanks for clarifying.

**Pull request closed without merging**
