### PR TITLE
Pass "follow" option to sass-graph (fixes 1952)

### LINKED ISSUE #1952: Recursive watch doesn't work for symlinked directories
I need to recursively watch a directory where one of subdirectories is symlinked (pointing somewhere outside the watched directory). For that I use the `--watch`, `--recursive` and `--follow` options.  This doesn't work for files in subdirectories of the symlinked directory.

Let's imagine a following setup:

* dir1/
    * dir2/ **<-- a symbolic link  to dir2/**
    * file1.scss
* dir2/
    * file2.scss
    * dir3/
        * file3.scss

Then if I run the following command:

     node-sass/bin/node-sass dir1 --output dir1 --follow -r --watch

* Changing `file1.scss` fill be noticed and will work as expected
* Changing `file2.scss` fill be noticed and will work as expected
* Changing `file3.scss` fill be completely ignored

The problem does not occur when not watching (i.e. when executing the command without `--watch`).

So far I only tested this on Mac OS X, which I feel might be significant.

# Version info
- NPM version (`npm -v`): 4.1.1
- Node version (`node -v`): v7.3.0
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '7.3.0',
  v8: '5.4.500.45',
  uv: '1.10.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2j',
  icu: '58.1',
  unicode: '9.0',
  cldr: '30.0.2',
  tz: '2016g' }
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass	4.5.2	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
- npm node-sass versions (`npm ls node-sass`):
└─┬ nativescript-dev-sass@1.1.0
  └── node-sass@4.5.2

### PR DESCRIPTION
**Pull request by ludwiktrammer**
See https://github.com/xzyfer/sass-graph/pull/74
Fixes #1952

### CODE REVIEW

**Comment by xzyfer** [comment]
This blocked on sass-graph@2.2.0 being released

**Comment by xzyfer** [comment]
sass-graph@2.2.0 has been released. I'm going to let it sit for a couple days to see if there are any issues before committing to it.

@ludwiktrammer this PR should also bump the min sass-graph version to `^2.2.0`.

**Comment by ludwiktrammer** [comment]
@xzyfer Any updates on timeline for merging this?

I didn't update the PR with `sass-graph` version bump, because when I wanted to do this, I noticed you already added #1958. Or should I do this anyway?

**Comment by xzyfer** [comment]
Don't worry about bumping sass-graph. The initial release had some issues.
I'm on holidays at the moment so I'm not sure when I'll get around to it.

On 3 May 2017 7:18 pm, "Ludwik Trammer" <notifications@github.com> wrote:

@xzyfer <https://github.com/xzyfer> Any updates on timeline for merging
this?

I didn't update the PR with sass-graph version bump, because when I wanted
to do this, I noticed you already added #1958
<https://github.com/sass/node-sass/pull/1958>. Or should I do this anyway?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/sass/node-sass/pull/1956#issuecomment-298976798>, or mute
the thread

**Comment by ludwiktrammer** [comment]
Sorry to bother you again, but what's the status on this?

**Comment by xzyfer** [comment]
I'm back from holidays now, slowly working through the back log. Shouldn't be long now. Apologies.

**Comment by xzyfer** [comment]
Thanks @ludwiktrammer, this fix is on master now.

**Pull request closed without merging**
